### ISSUE TITLE
Drop support for Tracker

### ISSUE THREAD

**Issue by mhauru** [TuringLang/Turing.jl#2356]
Some things to remove
* [ ] https://github.com/TuringLang/docs/issues/521
* [ ] Any other reference to Tracker in the docs
* [x] export of `AutoTracker`.
* [x] some tests still cover Tracker. Could leave them though if they are fast and harmless, maybe leave comments saying that if they ever need fixing, they should rather be deleted.
* [ ] something else? Please add.

**Comment by penelopeysm** [comment]
Replacing Tracker with Mooncake in docs is blocked, because that depends on Turing 0.35, and it's not possible right now to get a fully compiling Julia environment for the docs. (essentially, we need to bump DPPL and Turing to run with Bijectors@0.14)

https://github.com/TuringLang/docs/issues/541

That said, I think the remaining issues are to do with docs, rather than the Turing library. Besides, I've already been keeping track of these on the issue above. So I think it's safe to close this in favour of the docs issue.
