### ISSUE TITLE
Refactoring `VarInfo`

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#377]
This is an umbrella issue for all `VarInfo` related issues.

- [x] Support void distribution type in `setval!(vi, value, vn)` #323 
- [ ] Merge `Trace.vi` and `vi`? #249 
- [x] Trace Replay #358 
- [x] Remove `VarInfo.index` #388 
- [x] Allow adding right-hand-side information to `VarName` #389 
- [x] More robust mechanism for deleting entries from `VarInfo` #391
- [x] Turn `VarInfo` into a sub-module.

**Comment by xukai92** [comment]
NOTE: remaining issues in this umbrella is planned to be solved in PR #407
