### ISSUE TITLE
Plan for release 0.20

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#689]
General:

- [x] MAP inference based on l-BFGS 
- [x] `gradient` interface inconsistent! #687
- [x] Replacing `algorithm.gid` with `algorithm.s::Selector` 
   - [x] #567, 
   - [x] #172,
- [ ] Standardising APIs between compiler and inference methods #634 #456
   - [x] Evaluating posterior #400
   - [ ] Default sampling behaviour #446
   - [x] Maximum a posterior for Turing models #605
- [x] Refactoring of the `Sampler` APIs #723  #746
   - [x] Add additional keyword arguments to the sample function #482
   - [x] Clean up IO interface #474
   - [ ] Better design of storing lp and le #277
   - [ ] Storing statistics on the particle weights #493, #406
   - [x] Logging in samplers / diagnosis statistics #599
   - [x] Pass number of parallel chains as an argument #582 #698
   - [x] Introduce MCMCSampler type #602
   - [x] Better adaptation configuration interface #491 
   - [x] Arguments to pass warmup sample size. #448
   - [x] NUTS adaptation samples appear in full chain #635
   - [x] Resume interface #566 + Provide a way to set the initial state of HMC #571
- [x] Type stable implementation of `VarInfo` https://github.com/TuringLang/Turing.jl/pull/742  #294
- [x] Integration with `AdvancedHMC` https://github.com/TuringLang/Turing.jl/pull/739
- [x] Remove spl = nothing #537 (Fixed by https://github.com/TuringLang/Turing.jl/pull/706)
- [x] Re-organise `test` folder to improve clarity #711
  - add a `test/numerical` test folder
- [x] VarInfo performance and model types #620
  - [x] VarInfo type stability
  - [x] Make alg.space type info of the alg #802
- [x] Completely eliminating `Real` from the model and pre-allocating #665
- [ ] Benchmarking: add a `benchmarks` folder, and improve benchmarking https://github.com/TuringLang/Turing.jl/issues/822 https://github.com/TuringLang/AdvancedHMC.jl/issues/22#issuecomment-476286583
- [ ] AdvancedSMC 
  - [ ] [Traces]: add a member field to `Trace` to mark reference particle #396
  - [ ] Merge SMC and PG? #222 
  - [ ] Merge `Trace.vi` and `vi`? #249
  - [ ] Particle Gibbs does not return log probability #643
- [ ] Compiler and VarInfo related: 
  - [x] Refactoring: remove `VarInfo.pred`? #510
  - [x] Compiler-generated aliases #533
  - [x] @VarName can be replaced with a function #514
  - [x] observe and assume #504
  - [x] Add interface to manipulate the `lp_` variable, see #754 .
  - [ ] Poor support of using columns in IO #207
  - [x] Unify and improve broadcasting for ~ macro #476
- [ ] Docstrings and unifying error messages https://github.com/TuringLang/Turing.jl/issues/828  #747
- [ ] Lessons learned and open questions to improve documentation #603
- [x] Fix Vectorisation issues:  #760  #761 #737

HMC related: 
- [x] Introduce a type for Hamiltonian #691
- [x] HMCDA numerical errors #628
- [x] Cache Cholesky decomposition to improve NUTS efficiency #653
- [x] Diagnosing HMC: Energy Distribution #454 

Autograd related:
- [x] Distributions are not compatible with AD (ForwardDiff/Flux.Tracker) #615
- [x] Make sure all distributions support AD where possible #674
  - [x] `MvNormal` and `Tracker` #717
  - [x] AD fails for MixtureModel #722

Misc issues:
- [x] Extract symbol and indices from `varname` string #721
- [x] Remove Flat distribution #315
-  ~~Replace consume and Tasks with Julia iterator #594~~
